## 벡터 만들기

In [2]:
import numpy as np

In [3]:
vector_row = np.array([1,2,3]) # 행이 하나인 벡터
vector_column = np.array([[1] 
                        ,[2]
                        ,[3]]) # 열이 하나인 벡터

In [5]:
print(type(vector_column)) # 클래스가 넘파이 어레이다.

<class 'numpy.ndarray'>


In [9]:
new_row = np.asarray([1,2,3])
# asarray는 넘파이 배열을 받았을 때는 새로운 배열을 생성하지 않는다.

new_row = np.asarray(vector_row)
new_row is vector_row

True

In [10]:
new_row = np.array(vector_row)
new_row is vector_row

False

In [11]:
# copy 메서드를 이용하면 의도가 분명해진다.
new_row = vector_row.copy()
new_row is vector_row

False

## 행렬만들기

In [7]:
matrix = np.array([[1,2],[1,2],[1,2]])
matrix

array([[1, 2],
       [1, 2],
       [1, 2]])

In [13]:
# 넘파이에 행렬 객체가 있다
# 사용하지 않는 이유 1.array가 넘파이의 표준 배열이다. 2. 대부분의 메서드는 array를 반환한다.
matrix_object = np.mat([[1,2],[1,2],[1,2]])
matrix_object

matrix([[1, 2],
        [1, 2],
        [1, 2]])

In [15]:
# 임의의 값을 갖는 배열
empty_matrix = np.empty((3,2))
empty_matrix

array([[5.e-324, 1.e-323],
       [5.e-324, 1.e-323],
       [5.e-324, 1.e-323]])

In [17]:
# 0으로 채워진 배열
# 1로 채워진 배열

zeros_matrix = np.zeros((3,2))
ones_matrix = np.ones((3,2))

display(zeros_matrix,ones_matrix)

array([[0., 0.],
       [0., 0.],
       [0., 0.]])

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

In [18]:
# 특정 값으로 채운 배열 만들기 : +를 이용한다.

seven_matrix = np.zeros((3,2)) + 7
seven_matrix

array([[7., 7.],
       [7., 7.],
       [7., 7.]])

In [19]:
# 특정 값으로 채운 배열 만들기2 : full 함수를 이용한다.

seven_matrix = np.full((3,2),7)
seven_matrix

array([[7, 7],
       [7, 7],
       [7, 7]])

## 희소행렬 만들기

In [20]:
from scipy import sparse 

In [22]:
matrix = np.array([[0,0],[0,1],[3,0]])
matrix

array([[0, 0],
       [0, 1],
       [3, 0]])

In [26]:
# CSR 행렬을 만든다.
matrix_sparse = sparse.csr_matrix(matrix)
print(matrix_sparse)

  (1, 1)	1
  (2, 0)	3


In [29]:
matrix_large = np.array([
    [0]*10,[0]+[1]+[0]*8,[3]+[0]*9
])
matrix_large

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 1, 0, 0, 0, 0, 0, 0, 0, 0],
       [3, 0, 0, 0, 0, 0, 0, 0, 0, 0]])

In [31]:
matrix_large_CSR = sparse.csr_matrix(matrix_large)
print(matrix_large_CSR)

  (1, 1)	1
  (2, 0)	3


In [ ]:
# 0이 많은 행렬의 경우 계산 비용감소를 위해 희소행렬을 만들어 사용한다.
# 희소행렬의 종류는 다양하고 무엇이 가장 좋다고 할 수 없다.

In [33]:
# 직접 입력하여 희소행렬 만들기
matrix_sparse_2 = sparse.csr_matrix(([1,3],([1,2],[1,0])),shape=[3,10])
print(matrix_sparse_2)

  (1, 1)	1
  (2, 0)	3


In [34]:
# 희소행렬 밀집 배열로 변경하기
matrix = matrix_sparse_2.toarray()
matrix

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 1, 0, 0, 0, 0, 0, 0, 0, 0],
       [3, 0, 0, 0, 0, 0, 0, 0, 0, 0]])

In [37]:
matrix = matrix_sparse_2.todense() # array가 아닌 matirx를 반환한다.
matrix

matrix([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
        [0, 1, 0, 0, 0, 0, 0, 0, 0, 0],
        [3, 0, 0, 0, 0, 0, 0, 0, 0, 0]])

## 원소 선택하기

In [44]:
vector = np.array([1,2,3,4,5,6])
matrix = np.array([[1,2,3]
                  ,[4,5,6]
                  ,[7,8,9]])

In [45]:
vector[2]

3

In [46]:
matrix[1,1]

5

In [47]:
vector[:]

array([1, 2, 3, 4, 5, 6])

In [48]:
vector[:3]

array([1, 2, 3])

In [49]:
matrix[:2,:]

array([[1, 2, 3],
       [4, 5, 6]])

In [50]:
matrix[:,1:2]

array([[2],
       [5],
       [8]])

In [52]:
matrix[[0,2]]

array([[1, 2, 3],
       [7, 8, 9]])

## 행렬 정보 확인하기
 - 행렬의 크기, 원소 개수, 차원

In [53]:
matrix = np.array([[1,2,3,4]
                  ,[5,6,7,8]
                  ,[9,10,11,12]])

In [54]:
matrix.shape

(3, 4)

In [56]:
matrix.size

12

In [55]:
matrix.ndim

2

In [57]:
print(matrix.dtype) # 원소의 데이터 타입

int64


In [58]:
print(matrix.itemsize) # 원소 하나가 차지하는 바이트 크기

8


In [60]:
print(matrix.nbytes) 배열 전체가 차지하는 바이트 크기

96


## 벡터화 연산 적용하기
 - 배열의 여러원소에 어떤 함수를 적용하고 싶습니다.

In [65]:
matrix = np.array([[1,2,3]
                  ,[4,5,6]
                  ,[7,8,9]])

In [66]:
add_100 = lambda i: i+100
vectorized_add_100 = np.vectorize(add_100)
matrix_add_100 = vectorized_add_100(matrix)
matrix_add_100

array([[101, 102, 103],
       [104, 105, 106],
       [107, 108, 109]])

In [67]:
matrix +100

array([[101, 102, 103],
       [104, 105, 106],
       [107, 108, 109]])

In [69]:
matrix + [100,102,104]

array([[101, 104, 107],
       [104, 107, 110],
       [107, 110, 113]])

In [70]:
matrix + [[100],[103],[106]]

array([[101, 102, 103],
       [107, 108, 109],
       [113, 114, 115]])

## 최댓값, 최솟값 찾기

In [71]:
np.max(matrix)

9

In [72]:
np.min(matrix)

1

In [73]:
np.max(matrix,axis=0)

array([7, 8, 9])

In [74]:
np.max(matrix, axis=1)

array([3, 6, 9])

In [76]:
vector_column = np.max(matrix, axis=1, keepdims=True)
vector_column

array([[3],
       [6],
       [9]])

In [77]:
matrix - vector_column

array([[-2, -1,  0],
       [-2, -1,  0],
       [-2, -1,  0]])

## 평균, 분산, 표준편차 구하기

In [78]:
matrix = np.array([[1,2,3]
                  ,[4,5,6]
                  ,[7,8,9]])

In [79]:
np.mean(matrix)

5.0

In [80]:
np.var(matrix)

6.666666666666667

In [81]:
np.std(matrix)

2.581988897471611

In [82]:
np.mean(matrix, axis=0)

array([4., 5., 6.])

In [83]:
np.std(matrix, ddof=1) # 자유도를 고려하여 계산

2.7386127875258306

In [84]:
import pandas as pd

In [88]:
df = pd.DataFrame(matrix.flatten()) # 알아서 자유도를 고려하여 계산
df.std()

0    2.738613
dtype: float64

## 배열 크기 바꾸기

In [90]:
matrix = np.array([[1,2,3]
                  ,[4,5,6]
                  ,[7,8,9]
                  ,[10,11,12]])

In [91]:
matrix.reshape(2,6)

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12]])

In [92]:
matrix.size

12

In [93]:
matrix.reshape(1,-1)

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12]])

In [94]:
matrix.reshape(12) # 1차원 배열로 바꾸기

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [95]:
matrix.reshape(-1)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [97]:
matrix.ravel()

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

## 벡터나 행렬 전치하기
 - 벡터나 행렬을 전치하기

In [98]:
matrix = np.array([[1,2,3]
                  ,[4,5,6]
                  ,[7,8,9]])

In [99]:
matrix.T

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

In [102]:
np.array([1,2,3,4,5,6]).T # 바뀌지 않는다.

array([1, 2, 3, 4, 5, 6])

In [105]:
np.array([[1,2,3,4,5,6]]).T # 2차원부터 가능

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6]])

In [106]:
matrix.transpose()

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

In [110]:
matrix = np.array([[[1,2]
                   ,[3,4]
                   ,[5,6]]
                  ,[[7,8]
                   ,[9,10]
                   ,[11,12]]])
matrix.shape

(2, 3, 2)

In [111]:
matrix.transpose((0,2,1)) # 3차원 이상에서 직접 지정할 수 있다. 

array([[[ 1,  3,  5],
        [ 2,  4,  6]],

       [[ 7,  9, 11],
        [ 8, 10, 12]]])

## 행렬 펼치기
- 행렬을 1차원으로 펼치기

In [112]:
matrix = np.array([[1,2,3],[4,5,6],[7,8,9]])

In [113]:
matrix.flatten() # 행 벡터로 만든다.

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [114]:
matrix.reshape(1,-1) # 배열의 뷰를 반환

array([[1, 2, 3, 4, 5, 6, 7, 8, 9]])

In [117]:
vector_reshaped = matrix.reshape(-1)
vector_flattened = matrix.flatten()

display(vector_reshaped,vector_flattened)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [123]:
matrix[0][0] = -1 # (0,0) 위치 원소를 바꾼다.
display(vector_reshaped, vector_flattened)

# reshape = 원본이 바뀌면 바뀐다.
# flatten = 원본 배열과 상관없다.

array([-1,  2,  3,  4,  5,  6,  7,  8,  9])

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

## 행렬의 랭크 구하기
- 행렬의 rank를 알아야 합니다.
- https://m.blog.naver.com/PostView.nhn?blogId=sw4r&logNo=221416614473&proxyReferer=https:%2F%2Fwww.google.co.kr%2F

In [124]:
matrix = np.array([[1,1,1]
                  ,[1,1,10]
                  ,[1,1,15]])

In [125]:
np.linalg.matrix_rank(matrix)

2

## 행렬식 계산하기
- ad - bc

In [2]:
import numpy as np
matrix = np.array([[1,2,3]
                  ,[2,4,6]
                  ,[3,8,9]])

In [3]:
np.linalg.det(matrix)

0.0

## 행렬의 대각원소 추출하기

In [4]:
matrix.diagonal()

array([1, 4, 9])

In [5]:
matrix.diagonal(offset=-1) # 대각원소 하나 아랫줄 구하기

array([2, 8])

## 행렬의 대각합 계산하기

In [6]:
matrix.trace()

14

In [8]:
sum(matrix.diagonal())

14

In [7]:
matrix.trace(offset=-1) # 대각원소 하나 아랫줄합 구하기

10

## 고윳값과 고유벡터 찾기
-https://angeloyeo.github.io/2019/07/17/eigen_vector.html

In [10]:
matrix = np.array([[1,-1,3]
                 ,[1,1,6]
                 ,[3,8,9]])

In [12]:
eigenvalues, eigenvectors = np.linalg.eig(matrix)
display(eigenvalues,eigenvectors)

array([13.55075847,  0.74003145, -3.29078992])

array([[-0.17622017, -0.96677403, -0.53373322],
       [-0.435951  ,  0.2053623 , -0.64324848],
       [-0.88254925,  0.15223105,  0.54896288]])

## 점곱 구하기
- 행렬곱

In [14]:
vector_a = np.array([1,2,3])
vector_b = np.array([4,5,6])

np.dot(vector_a,vector_b)

32

In [15]:
vector_a @ vector_b

32

In [17]:
np.dot(1,2) # @와 np.dot의 차이 -> @는 행렬곱만을 의미한다. 스칼라 값에 대하여 적용이 불가능하다.

2

## 행렬 덧셈과 뺄셈

In [21]:
matrix_a = np.array([[1,1,1]
                    ,[1,1,1]
                    ,[1,1,2]])
matrix_b = np.array([[1,3,1]
                    ,[1,3,1]
                    ,[1,3,8]])

In [22]:
np.add(matrix_a, matrix_b)

array([[ 2,  4,  2],
       [ 2,  4,  2],
       [ 2,  4, 10]])

In [23]:
-matrix_a

array([[-1, -1, -1],
       [-1, -1, -1],
       [-1, -1, -2]])

In [24]:
np.subtract(matrix_a, matrix_b)

array([[ 0, -2,  0],
       [ 0, -2,  0],
       [ 0, -2, -6]])

## 행렬의 곱셈

In [25]:
matrix_a = np.array([[1,1],[1,2]])
matrix_b = np.array([[1,3],[1,2]])

In [26]:
np.dot(matrix_a,matrix_b)

array([[2, 5],
       [3, 7]])

In [27]:
matrix_a @ matrix_b

array([[2, 5],
       [3, 7]])

In [28]:
# 다차원 곱셈
# 앞 행렬의 마지막 배열과 뒤 행렬 마지막에서 두번째 배열의 차원이 같아야합니다
a = np.random.rand(2,1,4,5) # (a, b, c, D)
b = np.random.rand(1,3,5,6) # (e, f, D, g)

np.dot(a,b) # 결과의 차원 = (a,b,c,f,g)

array([[[[[[1.59996956, 0.8872881 , 1.32854597, 1.73768279,
            1.60029787, 1.58264068],
           [1.19231651, 0.96553944, 1.51324257, 0.95906597,
            1.79908818, 0.62805047],
           [1.82406319, 2.01012339, 1.23780398, 1.05960069,
            1.78789674, 1.59467651]]],


         [[[2.39505501, 1.52128911, 1.66792426, 2.11185145,
            2.2090079 , 1.79334355],
           [2.05444382, 1.67826271, 2.4528645 , 1.56713086,
            1.97179882, 0.69021115],
           [2.43143908, 2.8806714 , 1.42552234, 1.56430797,
            2.05733488, 2.32748594]]],


         [[[2.2443423 , 1.22175262, 1.70794369, 2.34155052,
            1.91957054, 1.98407643],
           [1.77216825, 1.50141557, 2.14101011, 1.32363752,
            2.02454291, 0.762163  ],
           [2.22585417, 2.63630329, 1.44067773, 1.25990193,
            1.97300658, 2.0411043 ]]],


         [[[1.75682966, 1.26701467, 1.01606702, 1.24082763,
            1.57741569, 0.9626733 ],
           [1.6208

 ## 역행렬

In [29]:
matrix = np.array([[1,4],[2,5]])

In [30]:
np.linalg.inv(matrix)

array([[-1.66666667,  1.33333333],
       [ 0.66666667, -0.33333333]])

In [31]:
matrix @ np.linalg.inv(matrix)

array([[1., 0.],
       [0., 1.]])

### 정방행렬이 아닌 행렬의 유사역행렬 구하기

In [32]:
matrix = np.array([[1,4,7],[2,5,8]])

In [33]:
np.linalg.pinv(matrix)

array([[-1.16666667,  1.        ],
       [-0.33333333,  0.33333333],
       [ 0.5       , -0.33333333]])

In [34]:
matrix @ np.linalg.pinv(matrix)

array([[1.00000000e+00, 3.55271368e-15],
       [1.77635684e-15, 1.00000000e+00]])

## 난수 생성하기

In [56]:
# 초깃값 설정하기
np.random.seed(0)

In [57]:
np.random.random(3) # 0.0 ~ 1.0 사이의 난수

array([0.5488135 , 0.71518937, 0.60276338])

In [58]:
np.random.randint(0,11,3) # 1 ~ 10 사이의 정수 난수

array([3, 7, 9])

In [59]:
np.random.normal(0.0,1.0,3) # 평균 = 0, 표준편차 = 1.0 인 정규분포를 기준으로 난수생성

array([-1.42232584,  1.52006949, -0.29139398])

In [60]:
np.random.logistic(0.0,1.0,3) # 평균 = 0, 스케일 = 1.0인 로지스틱 분포를 기준으로 난수 생성

array([-0.98118713, -0.08939902,  1.46416405])

In [61]:
np.random.uniform(1.0,2.0,3) # 1.0 <= x < 2.0 인 난수

array([1.47997717, 1.3927848 , 1.83607876])

In [62]:
np.random.random_sample((2,3))

array([[0.33739616, 0.64817187, 0.36824154],
       [0.95715516, 0.14035078, 0.87008726]])

In [63]:
np.random.random((2,3))

array([[0.47360805, 0.80091075, 0.52047748],
       [0.67887953, 0.72063265, 0.58201979]])

In [64]:
np.random.rand(2,3)

array([[0.53737323, 0.75861562, 0.10590761],
       [0.47360042, 0.18633234, 0.73691818]])

In [65]:
np.random.standard_normal((2,3))

array([[-0.13309028, -0.44423283, -0.34518616],
       [-0.88180055, -0.44265324, -0.5409163 ]])

In [66]:
np.random.choice([0,1,2],5) # 배열에서 지정 횟수만큼 랜덤하게 뽑는다.

array([0, 1, 2, 2, 0])

In [68]:
a = np.array([0,1,2,3,4])
np.random.shuffle(a) # 주어진 배열 a의 순서를 재배열한다.
a 

array([1, 0, 4, 2, 3])

In [69]:
a = np.array([0,1,2,3,4])
np.random.permutation(a) # 주어진 배열을 재배열한 배열을 반환한다. a는 변하지 않는다.

array([4, 1, 2, 0, 3])

In [70]:
np.random.permutation(5) # 0 부터 입력된 숫자 만큼의 정수를 랜덤 배열로 생성한다.

array([3, 0, 2, 1, 4])