In [1]:
import pandas as pd
from pandas import Series,DataFrame

# Series

In [3]:
obj = pd.Series([4,7,-5,-3])
obj

0    4
1    7
2   -5
3   -3
dtype: int64

In [4]:
obj.values,obj.index

(array([ 4,  7, -5, -3], dtype=int64), RangeIndex(start=0, stop=4, step=1))

In [6]:
obj2 = pd.Series([4,5,6,7],index=['d','e','f','g'])
obj2

d    4
e    5
f    6
g    7
dtype: int64

In [10]:
obj2[['d','f']]

d    4
f    6
dtype: int64

In [12]:
obj2[obj2>5]

f    6
g    7
dtype: int64

In [13]:
obj2*2

d     8
e    10
f    12
g    14
dtype: int64

In [16]:
import numpy as np
np.exp(obj2) # e(초월수) 의 지수승

d      54.598150
e     148.413159
f     403.428793
g    1096.633158
dtype: float64

In [19]:
np.e**7

1096.6331584284583

In [20]:
'f' in obj2

True

In [22]:
6 in obj2.values

True

In [23]:
dict_my = {'Ohio':35000,'Texas':71000,'Orange':16000,'Utah':5000}
obj3 = pd.Series(dict_my)
obj3

Ohio      35000
Texas     71000
Orange    16000
Utah       5000
dtype: int64

In [25]:
states = ['Califonia','Ohio','Orange','Texas']
obj4 = pd.Series(dict_my,index=states)
obj4

Califonia        NaN
Ohio         35000.0
Orange       16000.0
Texas        71000.0
dtype: float64

In [26]:
pd.isnull(obj4)

Califonia     True
Ohio         False
Orange       False
Texas        False
dtype: bool

In [32]:
pd.notnull(obj4)

Califonia    False
Ohio          True
Orange        True
Texas         True
dtype: bool

In [33]:
obj4.isnull()

Califonia     True
Ohio         False
Orange       False
Texas        False
dtype: bool

In [35]:
obj4.notnull()

Califonia    False
Ohio          True
Orange        True
Texas         True
dtype: bool

In [36]:
obj3 + obj4 # index가 같은 것끼리 연산된다.

Califonia         NaN
Ohio          70000.0
Orange        32000.0
Texas        142000.0
Utah              NaN
dtype: float64

In [40]:
obj4.name = 'population'
obj4.index.name = 'state'
obj4

state
Califonia        NaN
Ohio         35000.0
Orange       16000.0
Texas        71000.0
Name: population, dtype: float64

In [41]:
obj

0    4
1    7
2   -5
3   -3
dtype: int64

In [43]:
obj.index = ['Bob','Steve','Jeff','Ryan']
obj

Bob      4
Steve    7
Jeff    -5
Ryan    -3
dtype: int64

# dataframe

In [44]:
data = {'state': ['Ohio', 'Ohio', 'Ohio', 'Nevada', 'Nevada', 'Nevada'],
        'year': [2000, 2001, 2002, 2001, 2002, 2003],
        'pop': [1.5, 1.7, 3.6, 2.4, 2.9, 3.2]}
frame = pd.DataFrame(data)

In [45]:
frame

state  year  pop
0    Ohio  2000  1.5
1    Ohio  2001  1.7
2    Ohio  2002  3.6
3  Nevada  2001  2.4
4  Nevada  2002  2.9
5  Nevada  2003  3.2

In [46]:
frame.head()

state  year  pop
0    Ohio  2000  1.5
1    Ohio  2001  1.7
2    Ohio  2002  3.6
3  Nevada  2001  2.4
4  Nevada  2002  2.9

In [48]:
pd.DataFrame(data, columns=['year','state','pop'])

year   state  pop
0  2000    Ohio  1.5
1  2001    Ohio  1.7
2  2002    Ohio  3.6
3  2001  Nevada  2.4
4  2002  Nevada  2.9
5  2003  Nevada  3.2

In [50]:
frame2 = pd.DataFrame(data, columns=['year','state','pop','debt'],index=['one','two','three','four','five','six'])
frame2

year   state  pop debt
one    2000    Ohio  1.5  NaN
two    2001    Ohio  1.7  NaN
three  2002    Ohio  3.6  NaN
four   2001  Nevada  2.4  NaN
five   2002  Nevada  2.9  NaN
six    2003  Nevada  3.2  NaN

In [52]:
frame2.columns

Index(['year', 'state', 'pop', 'debt'], dtype='object')

In [53]:
frame2['state']

one        Ohio
two        Ohio
three      Ohio
four     Nevada
five     Nevada
six      Nevada
Name: state, dtype: object

In [54]:
frame2.year

one      2000
two      2001
three    2002
four     2001
five     2002
six      2003
Name: year, dtype: int64

In [56]:
frame2.loc['three']

year     2002
state    Ohio
pop       3.6
debt      NaN
Name: three, dtype: object

In [58]:
frame2['debt'] = 16.5
frame2

year   state  pop  debt
one    2000    Ohio  1.5  16.5
two    2001    Ohio  1.7  16.5
three  2002    Ohio  3.6  16.5
four   2001  Nevada  2.4  16.5
five   2002  Nevada  2.9  16.5
six    2003  Nevada  3.2  16.5

In [59]:
frame2['debt'] = np.arange(6.)
frame2

year   state  pop  debt
one    2000    Ohio  1.5   0.0
two    2001    Ohio  1.7   1.0
three  2002    Ohio  3.6   2.0
four   2001  Nevada  2.4   3.0
five   2002  Nevada  2.9   4.0
six    2003  Nevada  3.2   5.0

In [60]:
# 대입

val = pd.Series([-1,3,4], index=['two','four','five'])
frame2['debt'] = val
frame2

year   state  pop  debt
one    2000    Ohio  1.5   NaN
two    2001    Ohio  1.7  -1.0
three  2002    Ohio  3.6   NaN
four   2001  Nevada  2.4   3.0
five   2002  Nevada  2.9   4.0
six    2003  Nevada  3.2   NaN

In [64]:
frame2['eastern'] = (frame2.state =='Ohio')
frame2

year   state  pop  debt  eastern
one    2000    Ohio  1.5   NaN     True
two    2001    Ohio  1.7  -1.0     True
three  2002    Ohio  3.6   NaN     True
four   2001  Nevada  2.4   3.0    False
five   2002  Nevada  2.9   4.0    False
six    2003  Nevada  3.2   NaN    False

In [65]:
del frame2['eastern']
frame2

year   state  pop  debt
one    2000    Ohio  1.5   NaN
two    2001    Ohio  1.7  -1.0
three  2002    Ohio  3.6   NaN
four   2001  Nevada  2.4   3.0
five   2002  Nevada  2.9   4.0
six    2003  Nevada  3.2   NaN

In [68]:
pop = {'Nevada':{2001:2.4,2002:2.9},'Ohio':{2000:1.5,2001:1.7,2002:3.6}}

frame3 = pd.DataFrame(pop)
frame3

Nevada  Ohio
2001     2.4   1.7
2002     2.9   3.6
2000     NaN   1.5

In [70]:
frame3.T # 행,열 바꾸기

2001  2002  2000
Nevada   2.4   2.9   NaN
Ohio     1.7   3.6   1.5

In [71]:
pd.DataFrame(pop, index=[2001,2002,2003])

Nevada  Ohio
2001     2.4   1.7
2002     2.9   3.6
2003     NaN   NaN

In [72]:
pdata = {'Ohio' : frame3['Ohio'][:-1], 'Nevada':frame3['Nevada'][:2]}

pd.DataFrame(pdata)

Ohio  Nevada
2001   1.7     2.4
2002   3.6     2.9

In [74]:
frame3.index.name = 'year';frame3.columns.name = 'state'
frame3

state  Nevada  Ohio
year               
2001      2.4   1.7
2002      2.9   3.6
2000      NaN   1.5

In [75]:
frame3.values

array([[2.4, 1.7],
       [2.9, 3.6],
       [nan, 1.5]])

In [76]:
frame2.values # dtype을 알아서 변경

array([[2000, 'Ohio', 1.5, nan],
       [2001, 'Ohio', 1.7, -1.0],
       [2002, 'Ohio', 3.6, nan],
       [2001, 'Nevada', 2.4, 3.0],
       [2002, 'Nevada', 2.9, 4.0],
       [2003, 'Nevada', 3.2, nan]], dtype=object)

In [77]:
obj = pd.Series(range(3),index=['a','b','c'])
index = obj.index
index

Index(['a', 'b', 'c'], dtype='object')

In [81]:
index[1] = 'd' # 수정불가

TypeError: Index does not support mutable operations

In [85]:
lables = pd.Index(np.arange(3))
lables

Int64Index([0, 1, 2], dtype='int64')

In [87]:
obj2 = pd.Series([7,8,9],index=lables)
obj2

0    7
1    8
2    9
dtype: int64

In [89]:
obj2.index is lables

True

In [90]:
frame3

state  Nevada  Ohio
year               
2001      2.4   1.7
2002      2.9   3.6
2000      NaN   1.5

In [91]:
frame3.columns

Index(['Nevada', 'Ohio'], dtype='object', name='state')

In [93]:
'Ohio' in frame3.columns

True

In [94]:
2003 in frame3.columns

False

In [95]:
dup_labels = pd.Index(['foo','foo','bar','bar']) # index 중복 가능

dup_labels

Index(['foo', 'foo', 'bar', 'bar'], dtype='object')

In [96]:
frame3

state  Nevada  Ohio
year               
2001      2.4   1.7
2002      2.9   3.6
2000      NaN   1.5

In [98]:
dup_labels.unique()

Index(['foo', 'bar'], dtype='object')

### reindex

In [99]:
obj = pd.Series([4,6,1,7], index=['a','b','c','d'])
obj

a    4
b    6
c    1
d    7
dtype: int64

In [101]:
obj2 = obj.reindex(['a','c','d','b','e'])
obj2

a    4.0
c    1.0
d    7.0
b    6.0
e    NaN
dtype: float64

In [102]:
obj3 = pd.Series(['blue','purple','yellow'], index=[0,2,4])
obj3

0      blue
2    purple
4    yellow
dtype: object

In [103]:
obj3.reindex(range(6),method='ffill') #NaN 값을 이전 값으로 채워준다.

0      blue
1      blue
2    purple
3    purple
4    yellow
5    yellow
dtype: object

In [104]:
frame = pd.DataFrame(np.arange(9).reshape((3,3)),index=['a','c','d'],columns=['Ohio','Texas','California'])
frame

Ohio  Texas  California
a     0      1           2
c     3      4           5
d     6      7           8

In [105]:
frame2 = frame.reindex(['a','b','c','d']) # df row index 변경
frame2

Ohio  Texas  California
a   0.0    1.0         2.0
b   NaN    NaN         NaN
c   3.0    4.0         5.0
d   6.0    7.0         8.0

In [110]:
states = ['Texas','Utah','California'] # df column index 변경
frame.reindex(columns=state)

Texas  Utah  California
a      1   NaN           2
c      4   NaN           5
d      7   NaN           8

In [118]:
frame.loc[['a','b','c','d'],states]

KeyError: 'Passing list-likes to .loc or [] with any missing labels is no longer supported, see https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#deprecate-loc-reindex-listlike'

### 삭제

In [120]:
obj = pd.Series(np.arange(5.), index=['a','b','c','d','e'])
obj

a    0.0
b    1.0
c    2.0
d    3.0
e    4.0
dtype: float64

In [121]:
new_obj = obj.drop('c')
new_obj

a    0.0
b    1.0
d    3.0
e    4.0
dtype: float64

In [122]:
obj.drop(['d','c'])

a    0.0
b    1.0
e    4.0
dtype: float64

In [123]:
data = pd.DataFrame(np.arange(16).reshape((4, 4)),
                    index=['Ohio', 'Colorado', 'Utah', 'New York'],
                    columns=['one', 'two', 'three', 'four'])
data

one  two  three  four
Ohio        0    1      2     3
Colorado    4    5      6     7
Utah        8    9     10    11
New York   12   13     14    15

In [124]:
data.drop(['Colorado','Ohio']) # row 삭제

one  two  three  four
Utah        8    9     10    11
New York   12   13     14    15

In [125]:
data.drop('two', axis=1) # column 삭제

one  three  four
Ohio        0      2     3
Colorado    4      6     7
Utah        8     10    11
New York   12     14    15

In [126]:
data.drop(['two','four'],axis='columns') # column 삭제2

one  three
Ohio        0      2
Colorado    4      6
Utah        8     10
New York   12     14

In [129]:
obj.drop('c',inplace=True) # 완전 삭제


KeyError: "['c'] not found in axis"

In [130]:
obj

a    0.0
b    1.0
d    3.0
e    4.0
dtype: float64

### indexing, selection, filtering

In [131]:
obj = pd.Series(np.arange(4.),index=['a','b','c','d'])
obj

a    0.0
b    1.0
c    2.0
d    3.0
dtype: float64

In [134]:
obj['b'],obj[1]

(1.0, 1.0)

In [135]:
obj[2:4]

c    2.0
d    3.0
dtype: float64

In [136]:
obj[['b','a','d']]

b    1.0
a    0.0
d    3.0
dtype: float64

In [137]:
obj[obj<2]

a    0.0
b    1.0
dtype: float64

In [138]:
obj['b':'c'] #끝 값을 포함한다.

b    1.0
c    2.0
dtype: float64

In [139]:
obj['b':'c'] = 5
obj

a    0.0
b    5.0
c    5.0
d    3.0
dtype: float64

In [140]:
data = pd.DataFrame(np.arange(16).reshape((4, 4)),
                    index=['Ohio', 'Colorado', 'Utah', 'New York'],
                    columns=['one', 'two', 'three', 'four'])
data

one  two  three  four
Ohio        0    1      2     3
Colorado    4    5      6     7
Utah        8    9     10    11
New York   12   13     14    15

In [141]:
data['two'] # column

Ohio         1
Colorado     5
Utah         9
New York    13
Name: two, dtype: int32

In [142]:
data[['three','four']] # column

three  four
Ohio          2     3
Colorado      6     7
Utah         10    11
New York     14    15

In [143]:
data[:2] # row

one  two  three  four
Ohio        0    1      2     3
Colorado    4    5      6     7

In [144]:
data[data['three']>5]

one  two  three  four
Colorado    4    5      6     7
Utah        8    9     10    11
New York   12   13     14    15

In [145]:
data <5

one    two  three   four
Ohio       True   True   True   True
Colorado   True  False  False  False
Utah      False  False  False  False
New York  False  False  False  False

In [147]:
data[data<5] = 0
data

one  two  three  four
Ohio        0    0      0     0
Colorado    0    5      6     7
Utah        8    9     10    11
New York   12   13     14    15

### loc, iloc

In [148]:
data.loc['Colorado',['two','three']] # row, column순

two      5
three    6
Name: Colorado, dtype: int32

In [151]:
data.iloc[2,[3,0,1]] # iloc 은 숫자로만 가능

four    11
one      8
two      9
Name: Utah, dtype: int32

In [152]:
data.iloc[2] # row

one       8
two       9
three    10
four     11
Name: Utah, dtype: int32

In [153]:
data.iloc[[1,2],[3,0,1]]

four  one  two
Colorado     7    0    5
Utah        11    8    9

In [154]:
data.loc[:'Utah','two']

Ohio        0
Colorado    5
Utah        9
Name: two, dtype: int32

In [156]:
data.iloc[:,:3][data.three>5]

one  two  three
Colorado    0    5      6
Utah        8    9     10
New York   12   13     14

### 정수 indexing

In [162]:
ser = pd.Series(np.arange(3.0))
ser
ser[-1] # 정수(-)는 에러

KeyError: -1

In [164]:
ser2 = pd.Series(np.arange(3.), index=['a','b','c'])
ser2[-1] # index에 정수를 사용하지 않을 경우 가능하다.

2.0

In [165]:
ser[:1]

0    0.0
dtype: float64

In [166]:
ser.loc[:1] # 세밀하게 사용하기 위해 함수이용

0    0.0
1    1.0
dtype: float64

In [171]:
ser2.iloc[:2]

a    0.0
b    1.0
dtype: float64

### 연산, 정렬

In [172]:
s1 = pd.Series([7.3, -2.5, 3.4, 1.5], index=['a', 'c', 'd', 'e'])
s2 = pd.Series([-2.1, 3.6, -1.5, 4, 3.1],
               index=['a', 'c', 'e', 'f', 'g'])
s1,s2

(a    7.3
 c   -2.5
 d    3.4
 e    1.5
 dtype: float64,
 a   -2.1
 c    3.6
 e   -1.5
 f    4.0
 g    3.1
 dtype: float64)

In [173]:
s1 + s2 # index가 같은 것끼리만 더한다.

a    5.2
c    1.1
d    NaN
e    0.0
f    NaN
g    NaN
dtype: float64

In [174]:
df1 = pd.DataFrame(np.arange(9.).reshape((3, 3)), columns=list('bcd'),
                   index=['Ohio', 'Texas', 'Colorado'])
df2 = pd.DataFrame(np.arange(12.).reshape((4, 3)), columns=list('bde'),
                   index=['Utah', 'Ohio', 'Texas', 'Oregon'])
df1,df2

(            b    c    d
 Ohio      0.0  1.0  2.0
 Texas     3.0  4.0  5.0
 Colorado  6.0  7.0  8.0,
           b     d     e
 Utah    0.0   1.0   2.0
 Ohio    3.0   4.0   5.0
 Texas   6.0   7.0   8.0
 Oregon  9.0  10.0  11.0)

In [176]:
df1+df2

b   c     d   e
Colorado  NaN NaN   NaN NaN
Ohio      3.0 NaN   6.0 NaN
Oregon    NaN NaN   NaN NaN
Texas     9.0 NaN  12.0 NaN
Utah      NaN NaN   NaN NaN

In [177]:
-df1

b    c    d
Ohio     -0.0 -1.0 -2.0
Texas    -3.0 -4.0 -5.0
Colorado -6.0 -7.0 -8.0

In [179]:
-df1.isnull()

b     c     d
Ohio      True  True  True
Texas     True  True  True
Colorado  True  True  True

In [180]:
df1 = pd.DataFrame(np.arange(12.).reshape((3, 4)),
                   columns=list('abcd'))
df2 = pd.DataFrame(np.arange(20.).reshape((4, 5)),
                   columns=list('abcde'))
df2.loc[1, 'b'] = np.nan
df1,df2

(     a    b     c     d
 0  0.0  1.0   2.0   3.0
 1  4.0  5.0   6.0   7.0
 2  8.0  9.0  10.0  11.0,
       a     b     c     d     e
 0   0.0   1.0   2.0   3.0   4.0
 1   5.0   NaN   7.0   8.0   9.0
 2  10.0  11.0  12.0  13.0  14.0
 3  15.0  16.0  17.0  18.0  19.0)

In [181]:
df1+df2

a     b     c     d   e
0   0.0   2.0   4.0   6.0 NaN
1   9.0   NaN  13.0  15.0 NaN
2  18.0  20.0  22.0  24.0 NaN
3   NaN   NaN   NaN   NaN NaN

In [183]:
df1.add(df2,fill_value=0)

a     b     c     d     e
0   0.0   2.0   4.0   6.0   4.0
1   9.0   5.0  13.0  15.0   9.0
2  18.0  20.0  22.0  24.0  14.0
3  15.0  16.0  17.0  18.0  19.0

In [184]:
1/df1

a         b         c         d
0    inf  1.000000  0.500000  0.333333
1  0.250  0.200000  0.166667  0.142857
2  0.125  0.111111  0.100000  0.090909

In [186]:
df1.reindex(columns=df2.columns, fill_value=0)

a    b     c     d  e
0  0.0  1.0   2.0   3.0  0
1  4.0  5.0   6.0   7.0  0
2  8.0  9.0  10.0  11.0  0

### Series, Dataframe 연산

In [187]:
arr = np.arange(12.).reshape((3,4))

arr

array([[ 0.,  1.,  2.,  3.],
       [ 4.,  5.,  6.,  7.],
       [ 8.,  9., 10., 11.]])

In [188]:
arr[0]

array([0., 1., 2., 3.])

In [189]:
arr-arr[0] # 각 row에 연산되었다. 브로드캐스팅

array([[0., 0., 0., 0.],
       [4., 4., 4., 4.],
       [8., 8., 8., 8.]])

In [190]:
frame = pd.DataFrame(np.arange(12.).reshape((4, 3)),
                     columns=list('bde'),
                     index=['Utah', 'Ohio', 'Texas', 'Oregon'])
series = frame.iloc[0]

frame,series

(          b     d     e
 Utah    0.0   1.0   2.0
 Ohio    3.0   4.0   5.0
 Texas   6.0   7.0   8.0
 Oregon  9.0  10.0  11.0,
 b    0.0
 d    1.0
 e    2.0
 Name: Utah, dtype: float64)

In [191]:
frame - series

b    d    e
Utah    0.0  0.0  0.0
Ohio    3.0  3.0  3.0
Texas   6.0  6.0  6.0
Oregon  9.0  9.0  9.0

In [192]:
series2 = pd.Series(range(3),index=['b','e','f'])
series2

b    0
e    1
f    2
dtype: int64

In [193]:
frame + series2 # row, column 상관없이 index일치가 우선

b   d     e   f
Utah    0.0 NaN   3.0 NaN
Ohio    3.0 NaN   6.0 NaN
Texas   6.0 NaN   9.0 NaN
Oregon  9.0 NaN  12.0 NaN

In [194]:
series3 = frame['d']
series3

Utah       1.0
Ohio       4.0
Texas      7.0
Oregon    10.0
Name: d, dtype: float64

In [195]:
frame.sub(series3, axis='index') # axis로 연산기준을 지정할 수 있다.(세로로 뺌)

b    d    e
Utah   -1.0  0.0  1.0
Ohio   -1.0  0.0  1.0
Texas  -1.0  0.0  1.0
Oregon -1.0  0.0  1.0

### function, mapping

In [196]:
frame = pd.DataFrame(np.random.randn(4, 3), columns=list('bde'),
                     index=['Utah', 'Ohio', 'Texas', 'Oregon'])
frame

b         d         e
Utah   -0.888029  0.181924  1.119670
Ohio   -0.637516 -0.306760 -0.034633
Texas   1.356377  0.012738 -0.149867
Oregon -0.264742 -0.563241  1.205731

In [197]:
np.abs(frame)

b         d         e
Utah    0.888029  0.181924  1.119670
Ohio    0.637516  0.306760  0.034633
Texas   1.356377  0.012738  0.149867
Oregon  0.264742  0.563241  1.205731

In [198]:
f = lambda x: x.max()-x.min()

In [199]:
frame.apply(f) # column 을 기준으로

b    2.244405
d    0.745166
e    1.355599
dtype: float64

In [200]:
frame.apply(f,axis='columns')

Utah      2.007698
Ohio      0.602883
Texas     1.506244
Oregon    1.768972
dtype: float64

In [205]:
def f(x):
    return pd.Series([x.max(),x.min()],index=['max','min'])

frame.apply(f)

b         d         e
max  1.356377  0.181924  1.205731
min -0.888029 -0.563241 -0.149867

In [211]:
f = lambda x:'%.2f'%x

In [212]:
frame.applymap(f)

b      d      e
Utah    -0.89   0.18   1.12
Ohio    -0.64  -0.31  -0.03
Texas    1.36   0.01  -0.15
Oregon  -0.26  -0.56   1.21

In [214]:
frame['e'].map(f) # map함수는 Series에만 사용가능

Utah       1.12
Ohio      -0.03
Texas     -0.15
Oregon     1.21
Name: e, dtype: object

### 정렬과 순위

In [215]:
obj = pd.Series(range(4),index=['d','a','b','c'])
obj

d    0
a    1
b    2
c    3
dtype: int64

In [216]:
obj.sort_index()

a    1
b    2
c    3
d    0
dtype: int64

In [217]:
frame = pd.DataFrame(np.arange(8).reshape((2, 4)),
                     index=['three', 'one'],
                     columns=['d', 'a', 'b', 'c'])
frame

d  a  b  c
three  0  1  2  3
one    4  5  6  7

In [218]:
frame.sort_index() # row 만 정렬됨

d  a  b  c
one    4  5  6  7
three  0  1  2  3

In [219]:
frame.sort_index(axis=1)

a  b  c  d
three  1  2  3  0
one    5  6  7  4

In [220]:
frame.sort_index(axis=1, ascending=False) # 내림차순

d  c  b  a
three  0  3  2  1
one    4  7  6  5

In [221]:
obj = pd.Series([-4,7,-3,2])
obj

0   -4
1    7
2   -3
3    2
dtype: int64

In [222]:
obj.sort_values()

0   -4
2   -3
3    2
1    7
dtype: int64

In [224]:
obj = pd.Series([4,np.nan,7,np.inf,-3,2]) # inf,nan 은 맨뒤로 
obj.sort_values()

4   -3.0
5    2.0
0    4.0
2    7.0
3    inf
1    NaN
dtype: float64

In [225]:
frame = pd.DataFrame({'b':[4,7,-3,2],'a':[0,1,0,1]})
frame

b  a
0  4  0
1  7  1
2 -3  0
3  2  1

In [227]:
frame.sort_values(by='b')

b  a
2 -3  0
3  2  1
0  4  0
1  7  1

In [228]:
frame.sort_values(by=['a','b'])

b  a
2 -3  0
0  4  0
3  2  1
1  7  1

In [229]:
obj = pd.Series([7,-5,7,4,2,0,4])
obj.rank() # 값 크기로 순위를 매긴다 공동순위는 평균을 반환

0    6.5
1    1.0
2    6.5
3    4.5
4    3.0
5    2.0
6    4.5
dtype: float64

In [231]:
obj.rank(method='first') # 정렬순으로 매긴다.(같은 값이면 먼저 입력된 순)

0    6.0
1    1.0
2    7.0
3    4.0
4    3.0
5    2.0
6    5.0
dtype: float64

In [232]:
obj.rank(ascending=False, method='max') # 내림차순(동률처리 별로인듯)

0    2.0
1    7.0
2    2.0
3    4.0
4    5.0
5    6.0
6    4.0
dtype: float64

In [233]:
frame = pd.DataFrame({'b': [4.3, 7, -3, 2], 'a': [0, 1, 0, 1],
                      'c': [-2, 5, 8, -2.5]})
frame

b  a    c
0  4.3  0 -2.0
1  7.0  1  5.0
2 -3.0  0  8.0
3  2.0  1 -2.5

In [234]:
frame.rank(axis='columns') # row 별 순위

b    a    c
0  3.0  2.0  1.0
1  3.0  1.0  2.0
2  1.0  2.0  3.0
3  3.0  2.0  1.0

### 중복색인

In [235]:
obj = pd.Series(range(5), index=['a','a','b','b','c'])
obj

a    0
a    1
b    2
b    3
c    4
dtype: int64

In [236]:
obj.index.is_unique # index가 구별가능한지 판별

False

In [237]:
obj['a']

a    0
a    1
dtype: int64

In [238]:
df = pd.DataFrame(np.random.randn(4,3), index=['a','a','b','b'])
df

0         1         2
a  1.653251 -0.431249  2.131742
a  0.776502  2.202345 -1.921862
b -0.133480  1.609956 -0.893937
b -0.248083  1.347314  1.849928

In [239]:
df.loc['b']

0         1         2
b -0.133480  1.609956 -0.893937
b -0.248083  1.347314  1.849928

### 통계 계산,요약

In [240]:
df = pd.DataFrame([[1.4, np.nan], [7.1, -4.5],
                   [np.nan, np.nan], [0.75, -1.3]],
                  index=['a', 'b', 'c', 'd'],
                  columns=['one', 'two'])
df

one  two
a  1.40  NaN
b  7.10 -4.5
c   NaN  NaN
d  0.75 -1.3

In [243]:
df.sum() # 한 column의 합

one    9.25
two   -5.80
dtype: float64

In [244]:
df.sum(axis='columns') # row 합 

a    1.40
b    2.60
c    0.00
d   -0.55
dtype: float64

In [250]:
df.mean(axis=1,skipna=False) # NaN을 계산에 넣어라

a      NaN
b    1.300
c      NaN
d   -0.275
dtype: float64

In [252]:
df

one  two
a  1.40  NaN
b  7.10 -4.5
c   NaN  NaN
d  0.75 -1.3

In [251]:
df.idxmax() #열에서 최대값을 갖는 행

one    b
two    d
dtype: object

In [253]:
df.cumsum() #누적합 

one  two
a  1.40  NaN
b  8.50 -4.5
c   NaN  NaN
d  9.25 -5.8

In [254]:
df.describe()

one       two
count  3.000000  2.000000
mean   3.083333 -2.900000
std    3.493685  2.262742
min    0.750000 -4.500000
25%    1.075000 -3.700000
50%    1.400000 -2.900000
75%    4.250000 -2.100000
max    7.100000 -1.300000

In [255]:
obj = pd.Series(['a','a','b','c']*4) # 수치데이터가 아닌 값의 통계
obj.describe()

count     16
unique     3
top        a
freq       8
dtype: object

### 상관관계와 공분산

In [258]:
import pandas_datareader as web


C:\Users\Playdata\anaconda3\lib\site-packages\pandas_datareader\compat\__init__.py:7: FutureWarning: pandas.util.testing is deprecated. Use the functions in the public API at pandas.testing instead.
  from pandas.util.testing import assert_frame_equal


In [259]:
all_data = {ticker:web.get_data_yahoo(ticker)
           for ticker in ['AAPL','IBM','MSFT','GOOG']}

In [260]:
price = pd.DataFrame({ticker:data['Adj Close'] for ticker,data in all_data.items()})
volume = pd.DataFrame({ticker:data['Volume'] for ticker,data in all_data.items()})

In [263]:
returns = price.pct_change() # 변화율
returns.tail()

AAPL       IBM      MSFT      GOOG
Date                                              
2020-06-17 -0.001392 -0.007990  0.003461  0.005822
2020-06-18  0.000398  0.000081  0.010708 -0.010447
2020-06-19 -0.005715 -0.013611 -0.005960 -0.002953
2020-06-22  0.026164 -0.011431  0.027774  0.014067
2020-06-23  0.021345 -0.013711  0.006681  0.008644

In [264]:
returns['MSFT'].corr(returns.IBM) # 상관관계

0.5941781779760698

In [265]:
returns['MSFT'].cov(returns.IBM) # 공분산

0.0001658519684689284

In [266]:
returns.corr() # 상관행렬

AAPL       IBM      MSFT      GOOG
AAPL  1.000000  0.527990  0.714039  0.644644
IBM   0.527990  1.000000  0.594178  0.526518
MSFT  0.714039  0.594178  1.000000  0.751829
GOOG  0.644644  0.526518  0.751829  1.000000

In [267]:
returns.cov() # 공분산 행렬

AAPL       IBM      MSFT      GOOG
AAPL  0.000333  0.000155  0.000226  0.000202
IBM   0.000155  0.000260  0.000166  0.000146
MSFT  0.000226  0.000166  0.000300  0.000224
GOOG  0.000202  0.000146  0.000224  0.000295

In [268]:
returns.corrwith(returns.IBM)

AAPL    0.527990
IBM     1.000000
MSFT    0.594178
GOOG    0.526518
dtype: float64

In [269]:
returns.corrwith(volume) # 다른 Series나 Dataframe과도 가능

AAPL   -0.139447
IBM    -0.113700
MSFT   -0.065171
GOOG   -0.039960
dtype: float64

In [273]:
obj = pd.Series(['c','a','d','a','a','b','b','c','c'])
uniques = obj.unique()
uniques

array(['c', 'a', 'd', 'b'], dtype=object)

In [274]:
obj.value_counts()

c    3
a    3
b    2
d    1
dtype: int64

In [275]:
pd.value_counts(obj.values, sort=False)

a    3
d    1
b    2
c    3
dtype: int64

In [277]:
mask = obj.isin(['b','c'])
mask

0     True
1    False
2    False
3    False
4    False
5     True
6     True
7     True
8     True
dtype: bool

In [278]:
obj[mask]

0    c
5    b
6    b
7    c
8    c
dtype: object

In [279]:
to_match = pd.Series(['c','a','b','b','c','a'])
unique_val = pd.Series(['c','b','a'])

pd.Index(unique_val).get_indexer(to_match)

array([0, 2, 1, 1, 0, 2], dtype=int64)