### 누락된 데이터

In [2]:
import pandas as pd
import numpy as np

In [3]:
string_data = pd.Series(['aardvark','artichoko',np.nan,'avocado'])
string_data

0     aardvark
1    artichoko
2          NaN
3      avocado
dtype: object

In [4]:
string_data.isnull()

0    False
1    False
2     True
3    False
dtype: bool

In [5]:
string_data[0] = None
string_data.isnull()

0     True
1    False
2     True
3    False
dtype: bool

In [6]:
from numpy import nan as NA

In [7]:
data = pd.Series([1,NA,3.5,NA,7])
data

0    1.0
1    NaN
2    3.5
3    NaN
4    7.0
dtype: float64

In [8]:
data.dropna()

0    1.0
2    3.5
4    7.0
dtype: float64

In [9]:
data[data.notnull()]

0    1.0
2    3.5
4    7.0
dtype: float64

In [10]:
data = pd.DataFrame([[1,6.5,3],[1,NA,NA],[NA,NA,NA],[NA,6.5,3]])
data

0    1    2
0  1.0  6.5  3.0
1  1.0  NaN  NaN
2  NaN  NaN  NaN
3  NaN  6.5  3.0

In [11]:
cleaned = data.dropna() # NaN을 하나라도 갖는 행은 삭제
data,cleaned

(     0    1    2
 0  1.0  6.5  3.0
 1  1.0  NaN  NaN
 2  NaN  NaN  NaN
 3  NaN  6.5  3.0,
      0    1    2
 0  1.0  6.5  3.0)

In [12]:
data.dropna(how='all') # 모두 NaN인 행만 삭제

0    1    2
0  1.0  6.5  3.0
1  1.0  NaN  NaN
3  NaN  6.5  3.0

In [13]:
data[4] = NA
data

0    1    2   4
0  1.0  6.5  3.0 NaN
1  1.0  NaN  NaN NaN
2  NaN  NaN  NaN NaN
3  NaN  6.5  3.0 NaN

In [14]:
data.dropna(axis=1,how='all')

0    1    2
0  1.0  6.5  3.0
1  1.0  NaN  NaN
2  NaN  NaN  NaN
3  NaN  6.5  3.0

In [15]:
df = pd.DataFrame(np.random.randn(7,3))
df

0         1         2
0 -0.151619  0.272806 -1.667391
1  0.680160  0.010663 -1.838372
2  1.530143 -1.341167 -0.896328
3  1.422837 -1.383212  0.261332
4 -1.191844  1.296594  0.234698
5  0.823999 -1.369631 -1.340064
6 -0.157954  0.759177  0.449235

In [16]:
df.iloc[:4,1] = NA
df.iloc[:2,2] = NA
df

0         1         2
0 -0.151619       NaN       NaN
1  0.680160       NaN       NaN
2  1.530143       NaN -0.896328
3  1.422837       NaN  0.261332
4 -1.191844  1.296594  0.234698
5  0.823999 -1.369631 -1.340064
6 -0.157954  0.759177  0.449235

In [17]:
df.dropna()

0         1         2
4 -1.191844  1.296594  0.234698
5  0.823999 -1.369631 -1.340064
6 -0.157954  0.759177  0.449235

In [18]:
df.dropna(thresh=2) # 값을 가진(NaN이 아닌)개수를 지정하여 그 이상인 row만 조회

0         1         2
2  1.530143       NaN -0.896328
3  1.422837       NaN  0.261332
4 -1.191844  1.296594  0.234698
5  0.823999 -1.369631 -1.340064
6 -0.157954  0.759177  0.449235

In [19]:
df.fillna(0) # 0채워 넣기

0         1         2
0 -0.151619  0.000000  0.000000
1  0.680160  0.000000  0.000000
2  1.530143  0.000000 -0.896328
3  1.422837  0.000000  0.261332
4 -1.191844  1.296594  0.234698
5  0.823999 -1.369631 -1.340064
6 -0.157954  0.759177  0.449235

In [20]:
df.fillna({1:0.5,2:0}) # column마다 처리 기준이 달라지게 할 수 있다.

0         1         2
0 -0.151619  0.500000  0.000000
1  0.680160  0.500000  0.000000
2  1.530143  0.500000 -0.896328
3  1.422837  0.500000  0.261332
4 -1.191844  1.296594  0.234698
5  0.823999 -1.369631 -1.340064
6 -0.157954  0.759177  0.449235

In [21]:
df.fillna(0,inplace=True) # 변환하여 df에 반영

In [22]:
df = pd.DataFrame(np.random.randn(6,3))
df.iloc[2:,1]=NA
df.iloc[4:,2]=NA
df

0         1         2
0  1.905979 -2.197722  0.940997
1  1.365057 -1.829245  0.443283
2 -1.258833       NaN  0.734144
3 -0.116213       NaN -1.181771
4  1.338142       NaN       NaN
5  1.023537       NaN       NaN

In [23]:
df.fillna(method='ffill')

0         1         2
0  1.905979 -2.197722  0.940997
1  1.365057 -1.829245  0.443283
2 -1.258833 -1.829245  0.734144
3 -0.116213 -1.829245 -1.181771
4  1.338142 -1.829245 -1.181771
5  1.023537 -1.829245 -1.181771

In [38]:
df.fillna(df.mean(0)) #열별 평균값으로 채우기

0         1         2
0  1.905979 -2.197722  0.940997
1  1.365057 -1.829245  0.443283
2 -1.258833 -2.013483  0.734144
3 -0.116213 -2.013483 -1.181771
4  1.338142 -2.013483  0.234163
5  1.023537 -2.013483  0.234163

In [30]:
df.mean(1)

0    0.216418
1   -0.006968
2   -0.262345
3   -0.648992
4    1.338142
5    1.023537
dtype: float64

## 데이터 변형

In [39]:
data = pd.DataFrame({'k1':['one','two']*3+['two'],'k2':[1,1,2,3,3,4,4]})
data

k1  k2
0  one   1
1  two   1
2  one   2
3  two   3
4  one   3
5  two   4
6  two   4

In [40]:
data.duplicated() # 중복여부 판단

0    False
1    False
2    False
3    False
4    False
5    False
6     True
dtype: bool

In [41]:
data.drop_duplicates() # 중복제거

k1  k2
0  one   1
1  two   1
2  one   2
3  two   3
4  one   3
5  two   4

In [43]:
data['v1'] = range(7)
data

k1  k2  v1
0  one   1   0
1  two   1   1
2  one   2   2
3  two   3   3
4  one   3   4
5  two   4   5
6  two   4   6

In [44]:
data.drop_duplicates(['k1']) # 지정 column 값이 중복인 경우 삭제(처음값만 남김)

k1  k2  v1
0  one   1   0
1  two   1   1

In [45]:
data.drop_duplicates(['k1','k2'],keep='last') # 마지막만 남김

k1  k2  v1
0  one   1   0
1  two   1   1
2  one   2   2
3  two   3   3
4  one   3   4
6  two   4   6

### 함수,매핑을 통한 변형

In [46]:
data = pd.DataFrame({'food': ['bacon', 'pulled pork', 'bacon',
                              'Pastrami', 'corned beef', 'Bacon',
                              'pastrami', 'honey ham', 'nova lox'],
                     'ounces': [4, 3, 12, 6, 7.5, 8, 3, 5, 6]})
data

food  ounces
0        bacon     4.0
1  pulled pork     3.0
2        bacon    12.0
3     Pastrami     6.0
4  corned beef     7.5
5        Bacon     8.0
6     pastrami     3.0
7    honey ham     5.0
8     nova lox     6.0

In [47]:
meat_to_animal = {
  'bacon': 'pig',
  'pulled pork': 'pig',
  'pastrami': 'cow',
  'corned beef': 'cow',
  'honey ham': 'pig',
  'nova lox': 'salmon'
}

In [50]:
lowercased = data['food'].str.lower()
lowercased

0          bacon
1    pulled pork
2          bacon
3       pastrami
4    corned beef
5          bacon
6       pastrami
7      honey ham
8       nova lox
Name: food, dtype: object

In [51]:
data['animal'] = lowercased.map(meat_to_animal)
data

food  ounces  animal
0        bacon     4.0     pig
1  pulled pork     3.0     pig
2        bacon    12.0     pig
3     Pastrami     6.0     cow
4  corned beef     7.5     cow
5        Bacon     8.0     pig
6     pastrami     3.0     cow
7    honey ham     5.0     pig
8     nova lox     6.0  salmon

In [52]:
data['food'].map(lambda x:meat_to_animal[x.lower()])

0       pig
1       pig
2       pig
3       cow
4       cow
5       pig
6       cow
7       pig
8    salmon
Name: food, dtype: object

### 값 치환하기

In [53]:
data = pd.Series([1.,-999,2,-999,-1000,3])
data

0       1.0
1    -999.0
2       2.0
3    -999.0
4   -1000.0
5       3.0
dtype: float64

In [55]:
data.replace(-999,NA) # 값 치환

0       1.0
1       NaN
2       2.0
3       NaN
4   -1000.0
5       3.0
dtype: float64

In [56]:
data.replace([-999,-1000],NA)

0    1.0
1    NaN
2    2.0
3    NaN
4    NaN
5    3.0
dtype: float64

In [57]:
data.replace([-999,-1000],[NA,0])

0    1.0
1    NaN
2    2.0
3    NaN
4    0.0
5    3.0
dtype: float64

In [58]:
data.replace({-999:NA, -1000:0})

0    1.0
1    NaN
2    2.0
3    NaN
4    0.0
5    3.0
dtype: float64

### column index 이름 바꾸기

In [60]:
data = pd.DataFrame(np.arange(12).reshape(3,4),index=['Ohio','Colorado','New York'],columns=['one','two','three','four'])
data

one  two  three  four
Ohio        0    1      2     3
Colorado    4    5      6     7
New York    8    9     10    11

In [61]:
transform = lambda x: x[:4].upper()

data.index.map(transform) # index에 map 함수 있다.

Index(['OHIO', 'COLO', 'NEW '], dtype='object')

In [63]:
data.index = data.index.map(transform) #index 변경

data

one  two  three  four
OHIO    0    1      2     3
COLO    4    5      6     7
NEW     8    9     10    11

In [64]:
data.rename(index=str.title,columns=str.upper) # 원래 data는 변하지 않는다.

ONE  TWO  THREE  FOUR
Ohio    0    1      2     3
Colo    4    5      6     7
New     8    9     10    11

In [65]:
data.rename(index={'Ohio':'INDIANA'},columns={'three':'peekaboo'})

one  two  peekaboo  four
OHIO    0    1         2     3
COLO    4    5         6     7
NEW     8    9        10    11

### 개별화,양자화

In [67]:
ages = [20,22,25,27,21,23,37,31,61,45,41,32]
bins = [18,25,35,60,100] # 그룹으로 나눌 기준

In [69]:
cats = pd.cut(ages,bins)
cats

[(18, 25], (18, 25], (18, 25], (25, 35], (18, 25], ..., (25, 35], (60, 100], (35, 60], (35, 60], (25, 35]]
Length: 12
Categories (4, interval[int64]): [(18, 25] < (25, 35] < (35, 60] < (60, 100]]

In [70]:
cats.codes # 나눈 값들을 숫자코드로 바꿔놓은것

array([0, 0, 0, 1, 0, 0, 2, 1, 3, 2, 2, 1], dtype=int8)

In [71]:
cats.categories # 항목

IntervalIndex([(18, 25], (25, 35], (35, 60], (60, 100]],
              closed='right',
              dtype='interval[int64]')

In [73]:
pd.value_counts(cats)

(18, 25]     5
(35, 60]     3
(25, 35]     3
(60, 100]    1
dtype: int64

In [77]:
group_names = ['Youth','YoungAdult','MiddleAged','Senior'] # 그룹별 이름 지정
cat = pd.cut(ages,bins,labels=group_names)
cat[0]

'Youth'

In [98]:
data = np.random.rand(20)
data

array([0.29574262, 0.34851094, 0.78723664, 0.35771696, 0.72457828,
       0.90626773, 0.50163646, 0.36458144, 0.22110234, 0.17611973,
       0.41876519, 0.53637146, 0.07817847, 0.03857434, 0.47828323,
       0.30302634, 0.35100677, 0.01476214, 0.71220253, 0.66571159])

In [100]:
pd.cut(data,5,precision=2) # 숫자로 입력하면 최대최솟값을 경계로 등분하여 준다. precision: 소수점 자릿수 제한

[(0.19, 0.37], (0.19, 0.37], (0.73, 0.91], (0.19, 0.37], (0.55, 0.73], ..., (0.19, 0.37], (0.19, 0.37], (0.014, 0.19], (0.55, 0.73], (0.55, 0.73]]
Length: 20
Categories (5, interval[float64]): [(0.014, 0.19] < (0.19, 0.37] < (0.37, 0.55] < (0.55, 0.73] < (0.73, 0.91]]

In [102]:
data = np.random.randn(1000)
data

array([ 1.63689028e-01,  8.79246196e-01,  7.03818245e-01,  1.25603061e+00,
        9.67904910e-02, -9.44680318e-01,  1.27632733e+00, -5.86830281e-02,
        1.04694707e+00, -4.98891034e-02, -1.82194289e+00, -7.54993478e-01,
        9.83261283e-01, -7.76679853e-01, -1.69488912e-01, -2.76305414e-01,
        6.11520548e-02,  3.98984977e-01,  9.07105622e-01, -5.64554220e-01,
       -1.01151810e-01, -5.25423490e-01, -7.55726870e-01,  1.48086938e+00,
       -8.88873985e-01, -6.84121818e-01, -3.91293678e-01, -1.28695360e+00,
        1.32751317e+00, -7.53028396e-01,  8.68929414e-01,  4.02125122e-01,
        7.34379961e-01,  2.27419954e-01,  5.18814144e-01,  1.27119105e+00,
       -4.21020335e-01, -4.14182354e-01,  4.34338774e-01,  5.75358664e-01,
        1.03083750e+00, -1.10669664e+00,  1.10535685e+00, -9.22210244e-02,
       -1.77777098e+00, -9.15482725e-01, -1.49628219e+00, -1.83744705e+00,
        5.28961414e-01, -8.28025967e-02,  1.01190698e+00,  2.47782441e-03,
        5.11178327e-01,  

In [104]:
cats = pd.qcut(data,4) # 4분위 값으로 나누기
cats

[(-0.0643, 0.571], (0.571, 2.882], (0.571, 2.882], (0.571, 2.882], (-0.0643, 0.571], ..., (0.571, 2.882], (-3.2199999999999998, -0.679], (-0.679, -0.0643], (-0.0643, 0.571], (-0.0643, 0.571]]
Length: 1000
Categories (4, interval[float64]): [(-3.2199999999999998, -0.679] < (-0.679, -0.0643] < (-0.0643, 0.571] < (0.571, 2.882]]

In [105]:
pd.value_counts(cats)

(0.571, 2.882]                   250
(-0.0643, 0.571]                 250
(-0.679, -0.0643]                250
(-3.2199999999999998, -0.679]    250
dtype: int64

In [106]:
pd.qcut(data,[0,0.1,0.5,0.9,1]) # 직접 지정도 가능하다.

[(-0.0643, 1.205], (-0.0643, 1.205], (-0.0643, 1.205], (1.205, 2.882], (-0.0643, 1.205], ..., (-0.0643, 1.205], (-1.22, -0.0643], (-1.22, -0.0643], (-0.0643, 1.205], (-0.0643, 1.205]]
Length: 1000
Categories (4, interval[float64]): [(-3.2199999999999998, -1.22] < (-1.22, -0.0643] < (-0.0643, 1.205] < (1.205, 2.882]]

### 특잇값을 찾고 제외하기

In [108]:
data = pd.DataFrame(np.random.randn(1000,4))
data.describe()

0            1            2            3
count  1000.000000  1000.000000  1000.000000  1000.000000
mean      0.032187     0.018913    -0.052726    -0.014956
std       1.032513     0.950051     1.018169     1.027998
min      -3.039219    -2.554556    -3.238828    -3.052849
25%      -0.673727    -0.625157    -0.771279    -0.661936
50%       0.056467     0.006823    -0.069238    -0.020608
75%       0.729644     0.660530     0.609147     0.657935
max       3.262793     3.385981     3.636632     3.302137

In [110]:
col = data[2]
col[np.fabs(col)>3]

60     3.290264
83    -3.023030
207   -3.017234
288   -3.238828
781    3.237503
958    3.636632
Name: 2, dtype: float64

In [116]:
data[(np.fabs(data)>3).any(1)] # 절댓값이 3이상인 값을 갖는 행 조회

0         1         2         3
60  -2.531915  0.804038  3.290264 -0.793980
83   0.745660  1.601376 -3.023030 -2.161774
162 -0.379945  0.064234 -0.392055  3.006279
207  0.394927 -0.152767 -3.017234  0.282655
246  0.317882 -0.741382 -0.385373  3.028111
288  0.136956 -0.190734 -3.238828 -0.797669
319  3.262793  0.921145 -0.012312  0.467349
353  0.385170  2.632474  0.366237  3.302137
608  0.671011 -0.052194  0.325479  3.159128
635 -3.039219  1.519489 -0.497300 -0.472006
650 -0.677871  3.234754 -1.974334 -0.194232
745  2.215067  3.385981 -0.191408  0.053311
781  1.025973  0.544530  3.237503  1.038577
797 -0.292259 -0.977320 -0.835351 -3.052849
856 -0.422389 -0.794304 -0.224627  3.071298
958 -0.184772  1.038984  3.636632 -0.850296

In [127]:
data[np.fabs(data)>3] = np.sign(data)*3 # 부호판별(np.sign)

In [128]:
data.describe()

0            1            2            3
count  1000.000000  1000.000000  1000.000000  1000.000000
mean      0.031963     0.018292    -0.053611    -0.015470
std       1.031607     0.947991     1.013558     1.026117
min      -3.000000    -2.554556    -3.000000    -3.000000
25%      -0.673727    -0.625157    -0.771279    -0.661936
50%       0.056467     0.006823    -0.069238    -0.020608
75%       0.729644     0.660530     0.609147     0.657935
max       3.000000     3.000000     3.000000     3.000000

In [130]:
np.sign(data).head()

0    1    2    3
0  1.0 -1.0 -1.0 -1.0
1 -1.0  1.0 -1.0  1.0
2  1.0  1.0 -1.0  1.0
3 -1.0  1.0  1.0  1.0
4  1.0 -1.0  1.0 -1.0

### 치환과 임의 샘플링

In [131]:
df = pd.DataFrame(np.arange(5*4).reshape((5,4)))
sampler = np.random.permutation(5)

In [132]:
df

0   1   2   3
0   0   1   2   3
1   4   5   6   7
2   8   9  10  11
3  12  13  14  15
4  16  17  18  19

In [133]:
df.take(sampler)

0   1   2   3
4  16  17  18  19
1   4   5   6   7
0   0   1   2   3
2   8   9  10  11
3  12  13  14  15

In [135]:
df.iloc[sampler]

0   1   2   3
4  16  17  18  19
1   4   5   6   7
0   0   1   2   3
2   8   9  10  11
3  12  13  14  15

In [138]:
df.sample(n=3) # 임의의 값으로 n개를 샘플링

0   1   2   3
3  12  13  14  15
2   8   9  10  11
4  16  17  18  19

In [139]:
choices =  pd.Series([5,7,-1,6,4])
draws = choices.sample(n=10,replace=True) # 복원 추출
draws

3    6
1    7
2   -1
0    5
3    6
0    5
1    7
4    4
0    5
2   -1
dtype: int64

### 표시자,더미변수 계산

In [141]:
df = pd.DataFrame({'key':['b','b','a','c','a','b'],'data1':range(6)})
df

key  data1
0   b      0
1   b      1
2   a      2
3   c      3
4   a      4
5   b      5

In [143]:
pd.get_dummies(df['key']) #더미 원핫!!!

a  b  c
0  0  1  0
1  0  1  0
2  1  0  0
3  0  0  1
4  1  0  0
5  0  1  0

In [145]:
dummies = pd.get_dummies(df['key'],prefix='key') # 이름 지정
dummies

key_a  key_b  key_c
0      0      1      0
1      0      1      0
2      1      0      0
3      0      0      1
4      1      0      0
5      0      1      0

In [147]:
df_with_dummy = df[['data1']].join(dummies)
df_with_dummy

data1  key_a  key_b  key_c
0      0      0      1      0
1      1      0      1      0
2      2      1      0      0
3      3      0      0      1
4      4      1      0      0
5      5      0      1      0

In [148]:
mnames = ['movie_id','title','genres']
movies = pd.read_table('./movies.dat',sep='::',header=None, names = mnames)

C:\Users\Playdata\anaconda3\lib\site-packages\ipykernel_launcher.py:2: ParserWarning: Falling back to the 'python' engine because the 'c' engine does not support regex separators (separators > 1 char and different from '\s+' are interpreted as regex); you can avoid this warning by specifying engine='python'.
  


In [150]:
movies.head(10)

movie_id                               title                        genres
0         1                    Toy Story (1995)   Animation|Children's|Comedy
1         2                      Jumanji (1995)  Adventure|Children's|Fantasy
2         3             Grumpier Old Men (1995)                Comedy|Romance
3         4            Waiting to Exhale (1995)                  Comedy|Drama
4         5  Father of the Bride Part II (1995)                        Comedy
5         6                         Heat (1995)         Action|Crime|Thriller
6         7                      Sabrina (1995)                Comedy|Romance
7         8                 Tom and Huck (1995)          Adventure|Children's
8         9                 Sudden Death (1995)                        Action
9        10                    GoldenEye (1995)     Action|Adventure|Thriller

In [153]:
all_genres = []

for x in movies.genres:
    all_genres.extend(x.split('|')) #리스트끼리의 합(리스트의 원소들을 앞 리스트에 넣는다.)
    
genres = np.unique(all_genres)

genres

array(['Action', 'Adventure', 'Animation', "Children's", 'Comedy',
       'Crime', 'Documentary', 'Drama', 'Fantasy', 'Film-Noir', 'Horror',
       'Musical', 'Mystery', 'Romance', 'Sci-Fi', 'Thriller', 'War',
       'Western'], dtype='<U11')

In [155]:
zero_matrix = np.zeros((len(movies),len(genres)))

dummies = pd.DataFrame(zero_matrix, columns = genres)

dummies

Action  Adventure  Animation  Children's  Comedy  Crime  Documentary  \
0        0.0        0.0        0.0         0.0     0.0    0.0          0.0   
1        0.0        0.0        0.0         0.0     0.0    0.0          0.0   
2        0.0        0.0        0.0         0.0     0.0    0.0          0.0   
3        0.0        0.0        0.0         0.0     0.0    0.0          0.0   
4        0.0        0.0        0.0         0.0     0.0    0.0          0.0   
...      ...        ...        ...         ...     ...    ...          ...   
3878     0.0        0.0        0.0         0.0     0.0    0.0          0.0   
3879     0.0        0.0        0.0         0.0     0.0    0.0          0.0   
3880     0.0        0.0        0.0         0.0     0.0    0.0          0.0   
3881     0.0        0.0        0.0         0.0     0.0    0.0          0.0   
3882     0.0        0.0        0.0         0.0     0.0    0.0          0.0   

      Drama  Fantasy  Film-Noir  Horror  Musical  Mystery  Romance  Sci-Fi  \
0       0.0      0.0        0.0     0.0      0.0      0.0      0.0     0.0   
1       0.0      0.0        0.0     0.0      0.0      0.0      0.0     0.0   
2       0.0      0.0        0.0     0.0      0.0      0.0      0.0     0.0   
3       0.0      0.0        0.0     0.0      0.0      0.0      0.0     0.0   
4       0.0      0.0        0.0     0.0      0.0      0.0      0.0     0.0   
...     ...      ...        ...     ...      ...      ...      ...     ...   
3878    0.0      0.0        0.0     0.0      0.0      0.0      0.0     0.0   
3879    0.0      0.0        0.0     0.0      0.0      0.0      0.0     0.0   
3880    0.0      0.0        0.0     0.0      0.0      0.0      0.0     0.0   
3881    0.0      0.0        0.0     0.0      0.0      0.0      0.0     0.0   
3882    0.0      0.0        0.0     0.0      0.0      0.0      0.0     0.0   

      Thriller  War  Western  
0          0.0  0.0      0.0  
1          0.0  0.0      0.0  
2          0.0  0.0      0.0  
3          0.0  0.0      0.0  
4          0.0  0.0      0.0  
...        ...  ...      ...  
3878       0.0  0.0      0.0  
3879       0.0  0.0      0.0  
3880       0.0  0.0      0.0  
3881       0.0  0.0      0.0  
3882       0.0  0.0      0.0  

[3883 rows x 18 columns]

In [156]:
gen = movies.genres[0]
gen.split('|')

['Animation', "Children's", 'Comedy']

In [157]:
dummies.columns.get_indexer(gen.split('|')) # col 위치 반환

array([2, 3, 4], dtype=int64)

In [158]:
for i,gen in enumerate(movies.genres):
    indices = dummies.columns.get_indexer(gen.split('|'))
    dummies.iloc[i,indices] = 1 

In [160]:
movies_windic = movies.join(dummies.add_prefix('Genre_'))

movies_windic.iloc[1]

movie_id                                        2
title                              Jumanji (1995)
genres               Adventure|Children's|Fantasy
Genre_Action                                    0
Genre_Adventure                                 1
Genre_Animation                                 0
Genre_Children's                                1
Genre_Comedy                                    0
Genre_Crime                                     0
Genre_Documentary                               0
Genre_Drama                                     0
Genre_Fantasy                                   1
Genre_Film-Noir                                 0
Genre_Horror                                    0
Genre_Musical                                   0
Genre_Mystery                                   0
Genre_Romance                                   0
Genre_Sci-Fi                                    0
Genre_Thriller                                  0
Genre_War                                       0


In [161]:
np.random.seed(12345)
values = np.random.rand(10)

values

array([0.92961609, 0.31637555, 0.18391881, 0.20456028, 0.56772503,
       0.5955447 , 0.96451452, 0.6531771 , 0.74890664, 0.65356987])

In [162]:
bins = [0,0.2,0.4,0.6,0.8,1]
pd.get_dummies(pd.cut(values, bins))

(0.0, 0.2]  (0.2, 0.4]  (0.4, 0.6]  (0.6, 0.8]  (0.8, 1.0]
0           0           0           0           0           1
1           0           1           0           0           0
2           1           0           0           0           0
3           0           1           0           0           0
4           0           0           1           0           0
5           0           0           1           0           0
6           0           0           0           0           1
7           0           0           0           1           0
8           0           0           0           1           0
9           0           0           0           1           0

## 문자열 다루기

In [163]:
val = 'a,b, guido'
val.split(',')

['a', 'b', ' guido']

In [166]:
pieces = [x.strip() for x in val.split(',')]
pieces

['a', 'b', 'guido']

In [168]:
'::'.join(pieces)

'a::b::guido'

In [170]:
'guido' in pieces

True

In [171]:
val.index(',')

1

In [172]:
val.find(':') # 없으면 -1

-1

In [174]:
val.index(':') # 없으면 error

ValueError: substring not found

In [175]:
val.count(',')

2

In [176]:
val.replace(',','::')

'a::b:: guido'

In [177]:
val.replace(',','')

'ab guido'

### 정규표현식

In [178]:
import re

text = 'foo bar\t baz \tqux'

re.split('\s+',text)

['foo', 'bar', 'baz', 'qux']

In [179]:
text = """Dave dave@google.com
Steve steve@gmail.com
Rob rob@gmail.com
Ryan ryan@yahoo.com
"""
pattern = r'[A-Z0-9._%+-]+@[A-Z0-9.-]+\.[A-Z]{2,4}'

In [180]:
regex = re.compile(pattern, flags=re.IGNORECASE) # re.IGNORECASE 대소문자를 가지리 않게한다.

In [181]:
regex.findall(text)

['dave@google.com', 'steve@gmail.com', 'rob@gmail.com', 'ryan@yahoo.com']

In [184]:
m = regex.search(text) # 처음 것만 찾음
m

<re.Match object; span=(5, 20), match='dave@google.com'>

In [185]:
text[m.start():m.end()]

'dave@google.com'

In [187]:
print(regex.match(text)) # 시작과 일치하는지 알려줌

None


In [188]:
print(regex.sub('REDACTED', text)) # 찾은 문자열 치환

Dave REDACTED
Steve REDACTED
Rob REDACTED
Ryan REDACTED



In [189]:
pattern = r'([A-Z0-9._%+-]+)@([A-Z0-9.-]+)\.([A-Z]{2,4})' # 괄호로 그룹나눔
regex = re.compile(pattern, flags=re.IGNORECASE)

In [191]:
m = regex.match('wesm@bright.net')
m.groups()

('wesm', 'bright', 'net')

In [192]:
regex.findall(text) # 그룹을 튜플로 묶어줌

[('dave', 'google', 'com'),
 ('steve', 'gmail', 'com'),
 ('rob', 'gmail', 'com'),
 ('ryan', 'yahoo', 'com')]

In [193]:
print(regex.sub(r'Username: \1, Domain: \2, Suffix: \3',text)) # \1 : 첫번째 그룹

Dave Username: dave, Domain: google, Suffix: com
Steve Username: steve, Domain: gmail, Suffix: com
Rob Username: rob, Domain: gmail, Suffix: com
Ryan Username: ryan, Domain: yahoo, Suffix: com



### pandas 벡터화된 문자열 함수

In [194]:
data = {'Dave': 'dave@google.com', 'Steve': 'steve@gmail.com',
        'Rob': 'rob@gmail.com', 'Wes': np.nan}
data = pd.Series(data)
data
data.isnull()

Dave     False
Steve    False
Rob      False
Wes       True
dtype: bool

In [200]:
data.str.contains('gmail')

Dave     False
Steve     True
Rob       True
Wes        NaN
dtype: object

In [201]:
data.str.findall(pattern, flags=re.IGNORECASE)

Dave     [(dave, google, com)]
Steve    [(steve, gmail, com)]
Rob        [(rob, gmail, com)]
Wes                        NaN
dtype: object

In [202]:
matches = data.str.match(pattern, flags=re.IGNORECASE)
matches

Dave     True
Steve    True
Rob      True
Wes       NaN
dtype: object

In [220]:
data.str.get(0) # index값으로 찾을 수 있다.

Dave       d
Steve      s
Rob        r
Wes      NaN
dtype: object

In [219]:
data.str[0]

Dave       d
Steve      s
Rob        r
Wes      NaN
dtype: object

In [221]:
data.str[:5] # 스플라이싱가능

Dave     dave@
Steve    steve
Rob      rob@g
Wes        NaN
dtype: object