In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import mglearn
from IPython.display import display
import seaborn as sns
from matplotlib import font_manager, rc, rcParams
from sklearn.model_selection import train_test_split
font_name = font_manager.FontProperties(fname="c:/Windows/Fonts/malgun.ttf").get_name()
rc('font', family=font_name)
rcParams['axes.unicode_minus'] = False
%matplotlib notebook

In [4]:
from sklearn.ensemble import GradientBoostingClassifier
from sklearn.datasets import make_circles

X,y = make_circles(noise=0.25, factor=0.5, random_state=1)

y_named = np.array(['blue','red'])[y]

X_train,X_test,y_train,y_test,y_train_named,y_test_named = train_test_split(X,y,y_named,random_state=0)

gbrt = GradientBoostingClassifier(random_state=0).fit(X_train,y_train_named)

## 결정함수

- decision_function : 양성(class = 1) 이라고 생각하는 정도를 나타냄


In [6]:
print('X_tset.shape',X_test.shape)
print('결정 함수 결과 형태 :',gbrt.decision_function(X_test).shape)

X_tset.shape (25, 2)
결정 함수 결과 형태 : (25,)


In [7]:
print('결정 함수:\n',gbrt.decision_function(X_test))

결정 함수:
 [ 4.13592603 -1.70169917 -3.95106099 -3.62609552  4.28986642  3.66166081
 -7.69097179  4.11001686  1.10753937  3.40782222 -6.46255955  4.28986642
  3.90156346 -1.20031247  3.66166081 -4.17231157 -1.23010079 -3.91576223
  4.03602783  4.11001686  4.11001686  0.65709014  2.69826265 -2.65673274
 -1.86776596]


In [9]:
print('임계치와 결정 함수 결과 비교:\n',gbrt.decision_function(X_test)>0)
print('예측:\n',gbrt.predict(X_test))

임계치와 결정 함수 결과 비교:
 [ True False False False  True  True False  True  True  True False  True
  True False  True False False False  True  True  True  True  True False
 False]
예측:
 ['red' 'blue' 'blue' 'blue' 'red' 'red' 'blue' 'red' 'red' 'red' 'blue'
 'red' 'red' 'blue' 'red' 'blue' 'blue' 'blue' 'red' 'red' 'red' 'red'
 'red' 'blue' 'blue']


In [14]:
greator_zero = (gbrt.decision_function(X_test)>0).astype(int)
pred = gbrt.classes_[greator_zero]
print('pred는 예측 결과와 같다:',np.all(pred == gbrt.predict(X_test)))

pred는 예측 결과와 같다: True


In [15]:
decision_function = gbrt.decision_function(X_test)
print('결정 함수 최솟값 : {:.2f} 최댓값 : {:.2f}'.format(np.min(decision_function),np.max(decision_function)))

결정 함수 최솟값 : -7.69 최댓값 : 4.29


## 예측 확률
- predict_proda

In [17]:
print('확률 값의 형태 :',gbrt.predict_proba(X_test).shape)

확률 값의 형태 : (25, 2)


In [19]:
print('예측 확률:\n',gbrt.predict_proba(X_test[:6]))

예측 확률:
 [[0.01573626 0.98426374]
 [0.84575653 0.15424347]
 [0.98112869 0.01887131]
 [0.97407033 0.02592967]
 [0.01352142 0.98647858]
 [0.02504637 0.97495363]]


## 다중분류에서의 불확실성

In [21]:
from sklearn.datasets import load_iris

iris = load_iris()
X_train,X_test,y_train,y_test = train_test_split(iris.data, iris.target, random_state=42)

gbrt = GradientBoostingClassifier(learning_rate=0.01,random_state=0).fit(X_train,y_train)

In [24]:
print('결정 함수의 결과형태 :', gbrt.decision_function(X_test).shape)
print('결정 함수 결과 :\n',gbrt.decision_function(X_test))

결정 함수의 결과형태 : (38, 3)
결정 함수 결과 :
 [[-1.995715    0.04758267 -1.92720695]
 [ 0.06146394 -1.90755736 -1.92793758]
 [-1.99058203 -1.87637861  0.09686725]
 [-1.995715    0.04758267 -1.92720695]
 [-1.99730159 -0.13469108 -1.20341483]
 [ 0.06146394 -1.90755736 -1.92793758]
 [-1.995715    0.04758267 -1.92720695]
 [-1.99677434 -1.87637861  0.09686725]
 [-1.995715    0.04758267 -1.92720695]
 [-1.995715    0.04758267 -1.92720695]
 [-1.99677434 -1.87637861  0.07863156]
 [ 0.06146394 -1.90755736 -1.92793758]
 [ 0.06146394 -1.90755736 -1.92793758]
 [ 0.06146394 -1.90755736 -1.92793758]
 [ 0.06146394 -1.90755736 -1.92793758]
 [-1.995715    0.04758267 -1.92720695]
 [-1.99087515 -1.87637861  0.09686725]
 [-1.995715    0.04758267 -1.92720695]
 [-1.995715    0.04758267 -1.92720695]
 [-1.99087515 -1.87637861  0.09686725]
 [ 0.06146394 -1.90755736 -1.92793758]
 [-1.99730159 -1.86429671  0.04166049]
 [ 0.06146394 -1.90755736 -1.92793758]
 [-1.99087515 -1.87637861  0.09686725]
 [-1.99087515 -1.87637861  0.0

In [26]:
print('가장 큰 결정함 수 인덱스:\n',np.argmax(gbrt.decision_function(X_test),axis=1))
print('예측: \n',gbrt.predict(X_test))
print(y_test)

가장 큰 결정함 수 인덱스:
 [1 0 2 1 1 0 1 2 1 1 2 0 0 0 0 1 2 1 1 2 0 2 0 2 2 2 2 2 0 0 0 0 1 0 0 2 1
 0]
예측: 
 [1 0 2 1 1 0 1 2 1 1 2 0 0 0 0 1 2 1 1 2 0 2 0 2 2 2 2 2 0 0 0 0 1 0 0 2 1
 0]
[1 0 2 1 1 0 1 2 1 1 2 0 0 0 0 1 2 1 1 2 0 2 0 2 2 2 2 2 0 0 0 0 1 0 0 2 1
 0]


In [27]:
print('예측 확률 :\n',gbrt.predict_proba(X_test)[:6,:])

예측 확률 :
 [[0.10217718 0.78840034 0.10942248]
 [0.78347147 0.10936745 0.10716108]
 [0.09818072 0.11005864 0.79176065]
 [0.10217718 0.78840034 0.10942248]
 [0.10360005 0.66723901 0.22916094]
 [0.78347147 0.10936745 0.10716108]]
